"""Steerable agent runtime — Tier 3 adapter package."""

from .chat_loop import (
    HOOK_SKIP,
    AssistantMessageCtx,
    BudgetExhaustedCtx,
    BudgetLimit,
    BudgetTracker,
    BudgetState,
    ChatLoop,
    CompletionDecision,
    CompletionStatus,
    ContentDeltaCtx,
    EmitCtx,
    ErrorCtx,
    HookCallback,
    HookContext,
    HookError,
    HookName,
    LoopConfig,
    LoopEndCtx,
    LoopStartCtx,
    MessageBoundaryStrategy,
    ProviderKind,
    RetryPolicy,
    RoundEndCtx,
    RoundStartCtx,
    SendMessagesCtx,
    ToolCallCtx,
    ToolResultCtx,
    consume_budget,
    decide_completion,
    is_retryable_error,
    next_retry_delay_ms,
)
from .errors import (
    BudgetExhaustedError,
    PolicyDeniedError,
    RuntimeError as SteerableRuntimeError,
    StorageError,
    ToolDispatchError,
    TransportError,
)
from .llm import LLMMessage, LLMProvider, LLMStreamChunk, LLMUsage
from .llm.anthropic_native import AnthropicProvider
from .llm.openai_compat import OpenAICompatProvider
from .storage import InMemoryStorage, StorageAdapter
from .tools import RegisteredTool, ToolRouter, tool
from .transport import (
    RuntimeSSEType,
    TransportAdapter,
    encode_legacy_compat_payload,
    encode_sse_event,
    encode_sse_event_bytes,
)

__all__ = [
    "BudgetExhaustedError",
    "PolicyDeniedError",
    "SteerableRuntimeError",
    "StorageError",
    "ToolDispatchError",
    "TransportError",
    "LLMMessage",
    "LLMProvider",
    "LLMStreamChunk",
    "LLMUsage",
    "OpenAICompatProvider",
    "AnthropicProvider",
    "RegisteredTool",
    "ToolRouter",
    "tool",
    "StorageAdapter",
    "InMemoryStorage",
    "TransportAdapter",
    "RuntimeSSEType",
    "encode_sse_event",
    "encode_sse_event_bytes",
    "encode_legacy_compat_payload",
    # ChatLoop (A1.1 — see spec/runtime/chat-loop.md)
    "ChatLoop",
    "LoopConfig",
    "ProviderKind",
    "CompletionStatus",
    "HookName",
    "HookCallback",
    "HOOK_SKIP",
    "HookError",
    "HookContext",
    "LoopStartCtx",
    "MessageBoundaryStrategy",
    "LoopEndCtx",
    "RoundStartCtx",
    "RoundEndCtx",
    "SendMessagesCtx",
    "ContentDeltaCtx",
    "AssistantMessageCtx",
    "ToolCallCtx",
    "ToolResultCtx",
    "EmitCtx",
    "BudgetExhaustedCtx",
    "ErrorCtx",
    # Re-exported from steerable_agent_harness for convenience.
    "BudgetLimit",
    "BudgetTracker",
    "BudgetState",
    "CompletionDecision",
    "RetryPolicy",
    "consume_budget",
    "decide_completion",
    "is_retryable_error",
    "next_retry_delay_ms",
]

__version__ = "0.1.0"
