"""Steerable agent runtime — Tier 3 adapter package."""

from .antihallucination import (
    AntiHallucinationConfig,
    AntiHallucinationHooks,
    detect_claimed_execution,
    detect_deferred_execution,
    detect_deferred_execution_eager,
    detect_execution_intent_in_user_message,
    parse_grounding_verdict,
    parse_turn_route,
    should_run_grounding_judge,
)
from .approval import (
    ApprovalDecision,
    ApprovalExecutor,
    ApprovalRequest,
    ApprovalStore,
    Approver,
    AutoApprover,
    InMemoryApprovalStore,
    JsonApprovalStore,
    SessionApprovalCache,
)
from .calibration import CalibratingProvider, ModelCalibration, UsageCalibration
from .compaction import CompactionHooks
from .errors import (
    ApprovalAborted,
    BudgetExhaustedError,
    PolicyDeniedError,
    StorageError,
    ToolDispatchError,
    TransportError,
)
from .errors import (
    RuntimeError as SteerableRuntimeError,
)
from .history import (
    CompactionBoundary,
    ContextFragment,
    ContextManager,
    HistoryItem,
    HistorySeed,
    HistoryStore,
    RecordEntry,
    entry_from_dict,
    entry_to_dict,
    message_from_dict,
    message_to_dict,
)
from .hooks import (
    ChainHooks,
    CompletionAction,
    CompletionDraft,
    LoopHooks,
    NoopHooks,
    PreStepAction,
    RetryAction,
    RewriteRequest,
    TranscriptAppend,
)
from .llm import (
    ContentPart,
    ImagePart,
    LLMMessage,
    LLMProvider,
    LLMStreamChunk,
    LLMUsage,
    TextPart,
    text_parts,
)
from .loop import (
    CompletionDecision,
    CoreLoop,
    LoopConfig,
    LoopContext,
    LoopEvent,
    RouterToolExecutor,
    ToolExecutor,
)
from .pseudo import extract_inline_tool_calls
from .recording import (
    DEFAULT_MAX_ITEM_TOKENS,
    InMemoryRequestSink,
    JsonlRequestSink,
    RecordedRequest,
    RecordingProvider,
    RequestSink,
    assert_bounded_items,
    assert_requests_match_record,
    assert_stable_prefix,
    load_recorded_requests,
)
from .replay import (
    ExecutionBudget,
    HarnessExecutionState,
    HarnessTrajectoryEvent,
    build_step_decision_event,
    reduce_execution_state,
)
from .otel import export_otlp_http, to_otlp_json
from .resume import load_history_transcript, load_transcript, project_transcript
from .retry import RetryHooks
from .skills import (
    EAGER_PRIORITY_THRESHOLD,
    FilesystemSkillProvider,
    SkillConfig,
    SkillDefinition,
    SkillExecutor,
    SkillHooks,
    SkillProvider,
    SkillSummary,
    matches_conditions,
    render_skill_catalog,
    select_catalog,
    skill_tool_descriptor,
)
from .spill import FilesystemSpillStore, InMemorySpillStore, SpillHooks, SpillStore
from .storage import StorageAdapter
from .subagent import SubagentConfig, SubagentExecutor, subagent_tool_descriptor
from .tokens import (
    MODEL_TOKEN_FACTORS,
    estimate_text_tokens,
    estimate_tokens,
    factor_for_model,
    register_model_factor,
)
from .tool_search import TOOL_SEARCH_NAME, register_tool_search, tool_search_descriptor
from .mcp import (
    DEFAULT_MAX_SERVER_TOOLS,
    McpCallResult,
    McpCatalogError,
    McpError,
    McpStdioClient,
    McpToolInfo,
    mcp_invoker,
    parse_mcp_name,
    qualify_mcp_name,
    register_mcp_catalog,
)
from .tools import RegisteredTool, ToolExposure, ToolRouter, tool
from .tracing import TraceRecorder
from .transport import TransportAdapter
from .world_state import (
    StaticWorldStateSection,
    WorldStateFragment,
    WorldStateHooks,
    WorldStatePatchFragment,
    WorldStateSection,
    apply_merge_patch,
    last_world_state_snapshot,
    merge_patch,
)

__all__ = [
    "AntiHallucinationConfig",
    "AntiHallucinationHooks",
    "ApprovalAborted",
    "ApprovalDecision",
    "ApprovalExecutor",
    "ApprovalRequest",
    "ApprovalStore",
    "Approver",
    "AutoApprover",
    "BudgetExhaustedError",
    "CalibratingProvider",
    "ChainHooks",
    "CompactionBoundary",
    "CompactionHooks",
    "CompletionAction",
    "CompletionDecision",
    "CompletionDraft",
    "ContentPart",
    "ContextFragment",
    "ContextManager",
    "CoreLoop",
    "DEFAULT_MAX_ITEM_TOKENS",
    "DEFAULT_MAX_SERVER_TOOLS",
    "EAGER_PRIORITY_THRESHOLD",
    "ExecutionBudget",
    "FilesystemSkillProvider",
    "FilesystemSpillStore",
    "HarnessExecutionState",
    "HarnessTrajectoryEvent",
    "HistoryItem",
    "HistorySeed",
    "HistoryStore",
    "ImagePart",
    "InMemoryApprovalStore",
    "InMemoryRequestSink",
    "InMemorySpillStore",
    "JsonApprovalStore",
    "JsonlRequestSink",
    "LLMMessage",
    "LLMProvider",
    "LLMStreamChunk",
    "LLMUsage",
    "LoopConfig",
    "LoopContext",
    "LoopEvent",
    "LoopHooks",
    "McpCallResult",
    "McpCatalogError",
    "McpError",
    "McpStdioClient",
    "McpToolInfo",
    "NoopHooks",
    "PolicyDeniedError",
    "PreStepAction",
    "RecordEntry",
    "RecordedRequest",
    "RecordingProvider",
    "RegisteredTool",
    "RequestSink",
    "RetryAction",
    "RetryHooks",
    "RewriteRequest",
    "RouterToolExecutor",
    "SessionApprovalCache",
    "SkillConfig",
    "SkillDefinition",
    "SkillExecutor",
    "SkillHooks",
    "SkillProvider",
    "SkillSummary",
    "SpillHooks",
    "SpillStore",
    "SteerableRuntimeError",
    "StorageAdapter",
    "StorageError",
    "SubagentConfig",
    "SubagentExecutor",
    "TOOL_SEARCH_NAME",
    "TextPart",
    "ToolDispatchError",
    "ToolExecutor",
    "ToolExposure",
    "MODEL_TOKEN_FACTORS",
    "ModelCalibration",
    "ToolRouter",
    "TraceRecorder",
    "TranscriptAppend",
    "estimate_text_tokens",
    "estimate_tokens",
    "export_otlp_http",
    "factor_for_model",
    "register_model_factor",
    "to_otlp_json",
    "TransportAdapter",
    "TransportError",
    "UsageCalibration",
    "StaticWorldStateSection",
    "WorldStateFragment",
    "WorldStateHooks",
    "WorldStatePatchFragment",
    "WorldStateSection",
    "apply_merge_patch",
    "assert_bounded_items",
    "assert_requests_match_record",
    "assert_stable_prefix",
    "build_step_decision_event",
    "detect_claimed_execution",
    "detect_deferred_execution",
    "detect_deferred_execution_eager",
    "detect_execution_intent_in_user_message",
    "extract_inline_tool_calls",
    "parse_grounding_verdict",
    "parse_turn_route",
    "entry_from_dict",
    "entry_to_dict",
    "last_world_state_snapshot",
    "load_history_transcript",
    "load_recorded_requests",
    "load_transcript",
    "matches_conditions",
    "mcp_invoker",
    "merge_patch",
    "message_from_dict",
    "message_to_dict",
    "parse_mcp_name",
    "project_transcript",
    "qualify_mcp_name",
    "reduce_execution_state",
    "register_mcp_catalog",
    "register_tool_search",
    "render_skill_catalog",
    "select_catalog",
    "should_run_grounding_judge",
    "skill_tool_descriptor",
    "subagent_tool_descriptor",
    "text_parts",
    "tool",
    "tool_search_descriptor",
]

__version__ = "0.1.0"
